[package]
name = "solitare"
version = "0.1.0"
authors = ["Ryan Van Gilder <rvangilder1@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_easings = "0.7"
rand = "0.8"
